packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
