name: guest
description: "HOMP Guest App — QR scan, browse menu, order, live tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.3
  mobile_scanner: ^5.2.3
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  pdf: ^3.10.8
  printing: ^5.11.4
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  nfc_manager: ^3.3.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  app_links: ^6.3.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
